Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 13, 2023 - 04:28:45
Django version 4.2.6, using settings 'src.settings'
Starting development server at http://127.0.0.1:8082/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 13, 2023 - 04:28:59
Django version 4.2.6, using settings 'src.settings'
Starting development server at http://127.0.0.1:8082/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Not Found: /
[13/Nov/2023 05:16:35] "GET / HTTP/1.1" 404 2636
Not Found: /
[13/Nov/2023 05:16:35] "GET / HTTP/1.1" 404 2636
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/ubuntu/ibas_project/ibas-data-analytics-panel-backend/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/ibas_project/ibas-data-analytics-panel-backend/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/ibas_project/ibas-data-analytics-panel-backend/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 261, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/ubuntu/ibas_project/ibas-data-analytics-panel-backend/env/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/ibas_project/ibas-data-analytics-panel-backend/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/ibas_project/ibas-data-analytics-panel-backend/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 231, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
  File "/home/ubuntu/ibas_project/ibas-data-analytics-panel-backend/env/lib/python3.8/site-packages/django/urls/base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/ubuntu/ibas_project/ibas-data-analytics-panel-backend/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 633, in app_dict
    self._populate()
  File "/home/ubuntu/ibas_project/ibas-data-analytics-panel-backend/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 570, in _populate
    url_pattern._populate()
  File "/home/ubuntu/ibas_project/ibas-data-analytics-panel-backend/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 543, in _populate
    for url_pattern in reversed(self.url_patterns):
TypeError: 'set' object is not reversible
[13/Nov/2023 05:17:52] "GET /admin/ HTTP/1.1" 500 95107
Not Found: /
[13/Nov/2023 05:18:12] "GET / HTTP/1.1" 404 2636
Not Found: /
[13/Nov/2023 05:18:16] "GET / HTTP/1.1" 404 2636
Not Found: /qa-dataset
[13/Nov/2023 05:18:31] "GET /qa-dataset HTTP/1.1" 404 2684
Performing system checks...

System check identified no issues (0 silenced).
November 13, 2023 - 05:16:30
Django version 4.2.6, using settings 'src.settings'
Starting development server at http://127.0.0.1:8082/
Quit the server with CONTROL-C.

